# Reading Excel Files With Multiple Sheets

In [14]:
import pandas as pd

In [15]:
# We have a excel file big_mart_sales_with_multiple_sheets.xlsx that contain different sheets for different years 1985, 1987, 1997
# Read the data with multiple sheets
data_with_multiple_sheets = pd.read_excel('big_mart_sales_with_multiple_sheets.xlsx')

In [16]:
# We can see that when we read the data with multiple sheets only the first sheet gets read.
data_with_multiple_sheets.shape

(1463, 12)

In [17]:
# To read the data from the specific sheet, we need to specify the sheet name.

sheet_1985 = pd.read_excel('big_mart_sales_with_multiple_sheets.xlsx',sheet_name='1985')
sheet_1987 = pd.read_excel('big_mart_sales_with_multiple_sheets.xlsx', sheet_name='1987')
sheet_1997 = pd.read_excel('big_mart_sales_with_multiple_sheets.xlsx', sheet_name='1997')

In [18]:
sheet_1985.shape, sheet_1987.shape, sheet_1997.shape

((1463, 12), (932, 12), (930, 12))

In [19]:
# The next step is to concatenate all sheets (create an array of dataframes)
all_dataframes = [sheet_1985, sheet_1987, sheet_1997]
all_dataframes

[     Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
 0              FDP10          NaN          Low Fat         0.127470
 1              DRI11          NaN          Low Fat         0.034238
 2              FDW12          NaN          Regular         0.035400
 3              FDC37          NaN          Low Fat         0.057557
 4              FDC14          NaN          Regular         0.072222
 ...              ...          ...              ...              ...
 1458           DRK37          NaN          Low Fat         0.043792
 1459           DRG13          NaN          Low Fat         0.037006
 1460           NCN14          NaN          Low Fat         0.091473
 1461           FDU44          NaN          Regular         0.102296
 1462           NCN18          NaN          Low Fat         0.124111

                   Item_Type  Item_MRP Outlet_Identifier  \
 0               Snack Foods  107.7622            OUT027
 1               Hard Drinks  113.2834            OUT027
 2              Baking Goods  144.5444            OUT027
 3              Baking Goods  107.6938            OUT019
 4                    Canned   43.6454            OUT019
 ...                     ...       ...               ...
 1458            Soft Drinks  189.0530            OUT027
 1459            Soft Drinks  164.7526            OUT027
 1460                 Others  184.6608            OUT027
 1461  Fruits and Vegetables  162.3552            OUT019
 1462              Household  111.7544            OUT027

       Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
 0                          1985      Medium               Tier 3
 1                          1985      Medium               Tier 3
 2                          1985      Medium               Tier 3
 3                          1985       Small               Tier 1
 4                          1985       Small               Tier 1
 ...                         ...         ...                  ...
 1458                       1985      Medium               Tier 3
 1459                       1985      Medium               Tier 3
 1460                       1985      Medium               Tier 3
 1461                       1985       Small               Tier 1
 1462                       1985      Medium               Tier 3

             Outlet_Type  Item_Outlet_Sales
 0     Supermarket Type3          4022.7636
 1     Supermarket Type3          2303.6680
 2     Supermarket Type3          4064.0432
 3         Grocery Store           214.3876
 4         Grocery Store           125.8362
 ...                 ...                ...
 1458  Supermarket Type3          6261.8490
 1459  Supermarket Type3          4111.3150
 1460  Supermarket Type3          2756.4120
 1461      Grocery Store           487.3656
 1462  Supermarket Type3          4138.6128

 [1463 rows x 12 columns],
     Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
 0             NCD19        8.930          Low Fat         0.000000
 1             FDO10       13.650          Regular         0.012741
 2             FDF32       16.350          Low Fat         0.068024
 3             FDN22       18.850          Regular         0.138190
 4             DRJ59       11.650          low fat         0.019356
 ..              ...          ...              ...              ...
 927           FDQ31        5.785          Regular         0.053802
 928           FDJ32       10.695          Low Fat         0.057744
 929           DRJ49        6.865          Low Fat         0.000000
 930           FDR26       20.700          Low Fat         0.042801
 931           FDF22        6.865          Low Fat         0.056783

                  Item_Type  Item_MRP Outlet_Identifier  \
 0                Household   53.8614            OUT013
 1              Snack Foods   57.6588            OUT013
 2    Fruits and Vegetables  196.4426            OUT013
 3              Snack Foods  250.8724            OUT013
 4              Hard Drinks   39.1164            OUT013
 ..                     ...       ...               ...
 927  Fruits and Vegetables   85.9856            OUT013
 928  Fruits and Vegetables   61.2536            OUT013
 929            Soft Drinks  129.9652            OUT013
 930                  Dairy  178.3028            OUT013
 931            Snack Foods  214.5218            OUT013

      Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
 0                         1987        High               Tier 3
 1                         1987        High               Tier 3
 2                         1987        High               Tier 3
 3                         1987        High               Tier 3
 4                         1987        High               Tier 3
 ..                         ...         ...                  ...
 927                       1987        High               Tier 3
 928                       1987        High               Tier 3
 929                       1987        High               Tier 3
 930                       1987        High               Tier 3
 931                       1987        High               Tier 3

            Outlet_Type  Item_Outlet_Sales
 0    Supermarket Type1           994.7052
 1    Supermarket Type1           343.5528
 2    Supermarket Type1          1977.4260
 3    Supermarket Type1          3775.0860
 4    Supermarket Type1           308.9312
 ..                 ...                ...
 927  Supermarket Type1          1494.0552
 928  Supermarket Type1           673.7896
 929  Supermarket Type1          2324.9736
 930  Supermarket Type1          2479.4392
 931  Supermarket Type1          2778.3834

 [932 rows x 12 columns],
     Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
 0             FDA03       18.500          Regular         0.045464
 1             FDS46       17.600          Regular         0.047257
 2             FDP49        9.000          Regular         0.069089
 3             FDR28       13.850          Regular         0.025896
 4             DRH01       17.500          Low Fat         0.097904
 ..              ...          ...              ...              ...
 925           FDC28        7.905          Low Fat         0.054987
 926           FDB17       13.150          Low Fat         0.036672
 927           FDT34        9.300          Low Fat         0.174350
 928           FDF53       20.750              reg         0.083607
 929           DRG01       14.800          Low Fat         0.044878

         Item_Type  Item_MRP Outlet_Identifier  Outlet_Establishment_Year  \
 0           Dairy  144.1102            OUT046                       1997
 1     Snack Foods  119.6782            OUT046                       1997
 2       Breakfast   56.3614            OUT046                       1997
 3    Frozen Foods  165.0210            OUT046                       1997
 4     Soft Drinks  174.8738            OUT046                       1997
 ..            ...       ...               ...                        ...
 925  Frozen Foods  108.6254            OUT046                       1997
 926  Frozen Foods  182.5976            OUT046                       1997
 927   Snack Foods  104.4964            OUT046                       1997
 928  Frozen Foods  178.8318            OUT046                       1997
 929   Soft Drinks   75.4670            OUT046                       1997

     Outlet_Size Outlet_Location_Type        Outlet_Type  Item_Outlet_Sales
 0         Small               Tier 1  Supermarket Type1          2187.1530
 1         Small               Tier 1  Supermarket Type1          2145.2076
 2         Small               Tier 1  Supermarket Type1          1547.3192
 3         Small               Tier 1  Supermarket Type1          4078.0250
 4         Small               Tier 1  Supermarket Type1          2085.2856
 ..          ...                  ...                ...                ...
 925       Small               Tier 1  Supermarket Type1          1844.9318
 926       Small               Tier 1  Supermarket Type1          4165.2448
 927       Small               Tier 1  Supermarket Type1          2419.5172
 928       Small               Tier 1  Supermarket Type1          3608.6360
 929       Small               Tier 1  Supermarket Type1           765.6700

 [930 rows x 12 columns]]

In [20]:
type(all_dataframes)

list

In [21]:
len(all_dataframes)

3

In [22]:
final_data = pd.concat(all_dataframes)

In [23]:
final_data.shape

(3325, 12)

In [24]:
final_data

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDP10,NaN,Low Fat,0.127470,Snack Foods,107.7622,OUT027,1985,Medium,Tier 3,Supermarket Type3,4022.7636
1,DRI11,NaN,Low Fat,0.034238,Hard Drinks,113.2834,OUT027,1985,Medium,Tier 3,Supermarket Type3,2303.6680
2,FDW12,NaN,Regular,0.035400,Baking Goods,144.5444,OUT027,1985,Medium,Tier 3,Supermarket Type3,4064.0432
3,FDC37,NaN,Low Fat,0.057557,Baking Goods,107.6938,OUT019,1985,Small,Tier 1,Grocery Store,214.3876
4,FDC14,NaN,Regular,0.072222,Canned,43.6454,OUT019,1985,Small,Tier 1,Grocery Store,125.8362
...,...,...,...,...,...,...,...,...,...,...,...,...
925,FDC28,7.905,Low Fat,0.054987,Frozen Foods,108.6254,OUT046,1997,Small,Tier 1,Supermarket Type1,1844.9318
926,FDB17,13.150,Low Fat,0.036672,Frozen Foods,182.5976,OUT046,1997,Small,Tier 1,Supermarket Type1,4165.2448
927,FDT34,9.300,Low Fat,0.174350,Snack Foods,104.4964,OUT046,1997,Small,Tier 1,Supermarket Type1,2419.5172
928,FDF53,20.750,reg,0.083607,Frozen Foods,178.8318,OUT046,1997,Small,Tier 1,Supermarket Type1,3608.6360
929,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700